def demo_profile() -> dict:
    return {
        "health": {
            "age": 43,
            "sex": "male",
            "height_cm": 172,
            "weight_kg": 82,
            "waist_cm": 93,
            "systolic_bp": 132,
            "diastolic_bp": 86,
            "fasting_glucose": 132,
            "bp_unknown": False,
            "glucose_unknown": False,
            "total_cholesterol": 218,
            "hdl": 42,
            "ldl": 138,
            "triglyceride": 185,
            "lipid_unknown": False,
        },
        "lifestyle": {
            "breakfast_per_week": 3,
            "sugary_drinks_per_week": 7,
            "late_meals_per_week": 3,
            "exercise_per_week": 1,
            "eating_out_per_week": 5,
            "sleep_hours": 6,
            "avg_steps": 4300,
            "smoking": "past",
            "drinking_per_week": 2,
            "drinking_per_month": 0,
            "drinks_per_session": 3,
            "available_minutes_per_day": 15,
        },
    }
